/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.userInterface;

import java.io.IOException;
import java.security.NoSuchAlgorithmException;

import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JOptionPane;

import org.backend.controllers.user.ChangePassword;
import org.backend.models.Manager;
import org.backend.models.User;
import org.backend.music.Music;
import org.backend.staticdata.SHA256;

/**
 *
 * A GUI to change passwords
 */
public class ChangePasswordPrompt extends javax.swing.JDialog {

    // Variables declaration - do not modify                     
    private javax.swing.JLabel cNewPassword;
    private javax.swing.JPasswordField cNewPasswordValue;
    private javax.swing.JPanel content;
    private javax.swing.JLabel formTitle;
    private javax.swing.JLabel newPassword;
    private javax.swing.JPasswordField newPasswordValue;
    private javax.swing.JLabel oldPassword;
    private javax.swing.JPasswordField oldPasswordValue;
    private javax.swing.JButton updateButton;

    static User loggedInUserGlobal;
    //static Manager managerGloabl;
    // End of variables declaration   

    /**
     * Creates new form ChangePassword
     */
    public ChangePasswordPrompt(javax.swing.JDialog parent, boolean modal, User loggedInUser) {
        super(parent, modal);
        loggedInUserGlobal = loggedInUser;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        content = new javax.swing.JPanel();
        formTitle = new javax.swing.JLabel();
        oldPassword = new javax.swing.JLabel();
        newPassword = new javax.swing.JLabel();
        cNewPassword = new javax.swing.JLabel();
        oldPasswordValue = new javax.swing.JPasswordField();
        newPasswordValue = new javax.swing.JPasswordField();
        cNewPasswordValue = new javax.swing.JPasswordField();
        updateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        content.setBackground(new java.awt.Color(0, 153, 153));
        
        formTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        formTitle.setText("Change Password");

        oldPassword.setText("Old Password");

        newPassword.setText("New Password");

        cNewPassword.setText("Confirm New Password");

        oldPasswordValue.setColumns(15);
        oldPasswordValue.setToolTipText("Enter the old password");

        newPasswordValue.setColumns(15);
        newPasswordValue.setToolTipText("Enter the new password");

        cNewPasswordValue.setColumns(15);
        cNewPasswordValue.setToolTipText("Please confirm the new password");

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    updateButtonActionPerformed(evt);
                } catch (NoSuchAlgorithmException e) {
                    e.printStackTrace();
                } catch (LineUnavailableException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                } catch (IOException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                } catch (UnsupportedAudioFileException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
            }
        });

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(formTitle))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(contentLayout.createSequentialGroup()
                                .addComponent(cNewPassword)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cNewPasswordValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                                .addComponent(newPassword)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(newPasswordValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createSequentialGroup()
                                .addComponent(oldPassword)
                                .addGap(107, 107, 107)
                                .addComponent(oldPasswordValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(updateButton)))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(formTitle)
                .addGap(41, 41, 41)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(oldPassword)
                    .addComponent(oldPasswordValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newPassword)
                    .addComponent(newPasswordValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cNewPassword)
                    .addComponent(cNewPasswordValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(updateButton)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) throws NoSuchAlgorithmException, LineUnavailableException, IOException, UnsupportedAudioFileException {                                             
        if (loggedInUserGlobal != null) {
            String oldPassword = String.valueOf(oldPasswordValue.getPassword());
            String newPassword = String.valueOf(newPasswordValue.getPassword());
            String confirmNewPassword = String.valueOf(cNewPasswordValue.getPassword());

            if (newPassword.equals(confirmNewPassword)) {
                String encryptedNewPassword = SHA256.getSHA(newPassword);
                String encryptedOldPassword = SHA256.getSHA(oldPassword);
                ChangePassword changePassword = new ChangePassword();
                boolean changePasswordSuccess = changePassword.changePassword(encryptedOldPassword,
                        encryptedNewPassword, loggedInUserGlobal);

                Manager manager = new Manager();
                if (changePasswordSuccess) {
                    System.out.println("Password changed successfully");
                    manager.loadAllData();
                    loggedInUserGlobal = manager.getLoggedInUser(loggedInUserGlobal.getId());
                    Music.playSound("src/main/java/org/backend/music/success.wav");
                    JOptionPane.showMessageDialog(null, "Password changed successfully");
                } else {
                    System.out.println("Something went wrong. Password change failed.");
                    Music.playSound("src/main/java/org/backend/music/invalid.wav");
                    JOptionPane.showMessageDialog(null, "Something went wrong. Password change failed.");

                }
            } else {
                System.out.println("Invalid Password. Please try again.");
                Music.playSound("src/main/java/org/backend/music/invalid.wav");
                JOptionPane.showMessageDialog(null, "Invalid Password. Please try again.");

            }
        } else {
            System.out.println("Please login first");
            Music.playSound("src/main/java/org/backend/music/invalid.wav");
            JOptionPane.showMessageDialog(null, "Please login first");
        }

        this.dispose();
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordPrompt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordPrompt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordPrompt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangePasswordPrompt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ChangePasswordPrompt dialog = new ChangePasswordPrompt(new javax.swing.JDialog(), true, loggedInUserGlobal);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

                    
}
