/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.userInterface;

import java.io.IOException;
import java.util.List;

import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.JOptionPane;

import org.backend.models.Account;
import org.backend.models.AccountSavings;
import org.backend.models.Customer;
import org.backend.models.Manager;
import org.backend.models.User;
import org.backend.music.Music;
import org.backend.staticdata.Data;

/**
 *
 * @author praneshjayasundar
 */
public class SavingsAccount extends javax.swing.JDialog {

    static User loggedInUserGlobal;
    //static Manager managerGlobal;
    // End of variables declaration
    /**
     * Creates new form SavingsAccount
     */
    public SavingsAccount(javax.swing.JDialog parent, boolean modal, User loggedInUser) {
        super(parent, modal);
        loggedInUserGlobal = loggedInUser;
        initComponents();
        setLocationRelativeTo(null);
        System.out.println(loggedInUser.getId());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        currencyGroup = new javax.swing.ButtonGroup();
        content = new javax.swing.JPanel();
        formTitle = new javax.swing.JLabel();
        customerId = new javax.swing.JLabel();
        accountBalance = new javax.swing.JLabel();
        customerIdValue = new javax.swing.JTextField();
        accountBalanceValue = new javax.swing.JTextField();
        createButton = new javax.swing.JButton();
        inr = new javax.swing.JRadioButton();
        euro = new javax.swing.JRadioButton();
        usd = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        formTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 24)); // NOI18N
        formTitle.setText("Create Savings Account");

        customerId.setText("Customer ID");

        accountBalance.setText("Account Balance");

        customerIdValue.setColumns(15);
        customerIdValue.setToolTipText("ID");
        customerIdValue.setText(String.valueOf(loggedInUserGlobal.getId()));
        customerIdValue.setEditable(false);

        accountBalanceValue.setColumns(15);
        accountBalanceValue.setToolTipText("Enter the account balance");

        createButton.setText("Create");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    createButtonActionPerformed(evt);
                } catch (LineUnavailableException | IOException | UnsupportedAudioFileException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
            }
        });

        currencyGroup.add(inr);
        inr.setText("INR");

        currencyGroup.add(euro);
        euro.setText("EUR");

        currencyGroup.add(usd);
        usd.setText("USD");

        jLabel1.setText("Currency");

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        content.setBackground(new java.awt.Color(0, 153, 153));
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(formTitle))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerId)
                            .addComponent(accountBalance)
                            .addComponent(jLabel1))
                        .addGap(63, 63, 63)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contentLayout.createSequentialGroup()
                                .addComponent(usd)
                                .addGap(18, 18, 18)
                                .addComponent(euro)
                                .addGap(18, 18, 18)
                                .addComponent(inr))
                            .addComponent(accountBalanceValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerIdValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createButton))))
                .addContainerGap(250, Short.MAX_VALUE))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(formTitle)
                .addGap(56, 56, 56)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerId)
                    .addComponent(customerIdValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountBalance)
                    .addComponent(accountBalanceValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(usd)
                    .addComponent(euro)
                    .addComponent(inr))
                .addGap(45, 45, 45)
                .addComponent(createButton)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) throws LineUnavailableException, IOException, UnsupportedAudioFileException {                                             
        String currencyUnit = "";
        if(!isDouble(accountBalanceValue.getText().toString())){
            JOptionPane.showMessageDialog(null, "Please enter a valid amount");
            return;
        }

        double accountBalance = Double.parseDouble(accountBalanceValue.getText());
        if(accountBalance < Data.initialSavingsAccountBalance){
            JOptionPane.showMessageDialog(null, "The minimum balance has to be "+Data.initialSavingsAccountBalance);
            return;
        }
        
        System.out.println(accountBalance);

        if(usd.isSelected()){
            System.out.println("Currency: USD");
            currencyUnit = usd.getText().toString();
        }
        else if(euro.isSelected()){
            System.out.println("Currency: EUR");
            currencyUnit = euro.getText().toString();
        }
        else if(inr.isSelected()){
            System.out.println("Currency: INR");
            currencyUnit = inr.getText().toString();
        }
        else{
            System.out.println("Currency: Null");
            JOptionPane.showMessageDialog(null, "Please select a currency");
            return;
        }
        
        System.out.println("value: "+currencyUnit);

        Manager manager = new Manager();

        //create the savings account for the user
        if (loggedInUserGlobal != null) {
            boolean createSavingsAccountSuccess = false;
            System.out.println("Enter Account Details");
            System.out.print("Account Balance: ");

            List<String> accountNumbers = manager.getAccountNumbers();
            
            Account savingsAccount = new AccountSavings(loggedInUserGlobal.getId(), Data.AccountTypes.SAVINGS.toString(), accountBalance, 1);
            createSavingsAccountSuccess = savingsAccount.createAccount(loggedInUserGlobal, accountNumbers, currencyUnit);
            if (createSavingsAccountSuccess) {
                System.out.println("Account created successfully");
                Music.playSound("src/main/java/org/backend/music/success.wav");
                JOptionPane.showMessageDialog(null, "Account created successfully");
                manager.loadAllData();
                loggedInUserGlobal = manager.getLoggedInUser(loggedInUserGlobal.getId());

            } else {
                System.out.println("Something went wrong. Account creation failed.");
            }
        } else {
            System.out.println("Please login first");
        }

        this.dispose();
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SavingsAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SavingsAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SavingsAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SavingsAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SavingsAccount dialog = new SavingsAccount(new javax.swing.JDialog(), true, loggedInUserGlobal);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel accountBalance;
    private javax.swing.JTextField accountBalanceValue;
    private javax.swing.JPanel content;
    private javax.swing.JButton createButton;
    private javax.swing.ButtonGroup currencyGroup;
    private javax.swing.JLabel customerId;
    private javax.swing.JTextField customerIdValue;
    private javax.swing.JRadioButton euro;
    private javax.swing.JLabel formTitle;
    private javax.swing.JRadioButton inr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton usd;
    // End of variables declaration
    
    boolean isDouble(String str) {
        try {
            Double.parseDouble(str);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
}
