/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.userInterface;

import java.io.IOException;
import java.security.NoSuchAlgorithmException;

import javax.swing.JOptionPane;

import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;

import org.backend.controllers.user.Signup;
import org.backend.models.Manager;
import org.backend.music.Music;
import org.backend.staticdata.SHA256;
/**
 *
 * @author praneshjayasundar
 */
public class SignUp extends javax.swing.JDialog {

     // Variables declaration - do not modify                     
     private javax.swing.JLabel address;
     private javax.swing.JTextArea addressValue;
     private javax.swing.JLabel admin;
     private javax.swing.JRadioButton adminNo;
     private javax.swing.JRadioButton adminYes;
     private javax.swing.JPasswordField cPasswordValue;
     private javax.swing.JLabel collateral;
     private javax.swing.JRadioButton collateralNo;
     private javax.swing.JRadioButton collateralYes;
     private javax.swing.JPanel content;
     private javax.swing.JLabel cpassword;
     private javax.swing.JLabel email;
     private javax.swing.JTextField emailValue;
     private javax.swing.JLabel employee;
     private javax.swing.JRadioButton employeeNo;
     private javax.swing.JRadioButton employeeYes;
     private javax.swing.JLabel firstName;
     private javax.swing.JTextField firstNameValue;
     private javax.swing.JLabel formTitle;
     private javax.swing.ButtonGroup hasCollateral;
     private javax.swing.ButtonGroup isAdmin;
     private javax.swing.ButtonGroup isEmployee;
     private javax.swing.JLabel lastName;
     private javax.swing.JTextField lastNameValue;
     private javax.swing.JLabel mobile;
     private javax.swing.JTextField mobileValue;
     private javax.swing.JLabel password;
     private javax.swing.JPasswordField passwordValue;
     private javax.swing.JButton reset;
     private javax.swing.JScrollPane scrollPane;
     private javax.swing.JButton submit;
     private javax.swing.JLabel successMsg;
     private javax.swing.JLabel userName;
     private javax.swing.JTextField userNameValue;
     //static Manager managerGlobal;

     // End of variables declaration
    /**
     * Creates new form SignUp
     */
    public SignUp(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        isEmployee = new javax.swing.ButtonGroup();
        isAdmin = new javax.swing.ButtonGroup();
        hasCollateral = new javax.swing.ButtonGroup();
        content = new javax.swing.JPanel();
        formTitle = new javax.swing.JLabel();
        lastName = new javax.swing.JLabel();
        firstName = new javax.swing.JLabel();
        userName = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        cpassword = new javax.swing.JLabel();
        mobile = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        address = new javax.swing.JLabel();
        lastNameValue = new javax.swing.JTextField();
        firstNameValue = new javax.swing.JTextField();
        passwordValue = new javax.swing.JPasswordField();
        userNameValue = new javax.swing.JTextField();
        cPasswordValue = new javax.swing.JPasswordField();
        mobileValue = new javax.swing.JTextField();
        emailValue = new javax.swing.JTextField();
        scrollPane = new javax.swing.JScrollPane();
        addressValue = new javax.swing.JTextArea();
        reset = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        employee = new javax.swing.JLabel();
        employeeYes = new javax.swing.JRadioButton();
        employeeNo = new javax.swing.JRadioButton();
        admin = new javax.swing.JLabel();
        adminYes = new javax.swing.JRadioButton();
        adminNo = new javax.swing.JRadioButton();
        successMsg = new javax.swing.JLabel();
        collateral = new javax.swing.JLabel();
        collateralYes = new javax.swing.JRadioButton();
        collateralNo = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        content.setName("Sign In"); // NOI18N

        content.setBackground(new java.awt.Color(0, 153, 153));

        formTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        formTitle.setText("BankApp Registration");

        lastName.setText("Last Name");

        firstName.setText("First Name");

        userName.setText("Username");

        password.setText("Password");

        cpassword.setText("Confirm Password");

        mobile.setText("Mobile");

        email.setText("Email");

        address.setText("Address");

        lastNameValue.setColumns(15);
        lastNameValue.setToolTipText("Last Name");

        firstNameValue.setColumns(15);
        firstNameValue.setToolTipText("First Name");

        passwordValue.setColumns(15);
        passwordValue.setToolTipText("Password");

        userNameValue.setColumns(15);
        userNameValue.setToolTipText("Username");
        userNameValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameValueActionPerformed(evt);
            }
        });

        cPasswordValue.setColumns(15);
        cPasswordValue.setToolTipText("Confirm Password must be same as the Password");

        mobileValue.setColumns(15);
        mobileValue.setToolTipText("Mobile Number should be exactly 10 digits");
        mobileValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileValueActionPerformed(evt);
            }
        });

        emailValue.setColumns(15);
        emailValue.setToolTipText("Email");

        addressValue.setColumns(15);
        addressValue.setRows(5);
        addressValue.setToolTipText("Address");
        scrollPane.setViewportView(addressValue);

        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    submitActionPerformed(evt);
                } catch (NoSuchAlgorithmException e) {
                    e.printStackTrace();
                } catch (UnsupportedAudioFileException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                } catch (LineUnavailableException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                } catch (IOException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
            }
        });

        employee.setText("Employee");

        isEmployee.add(employeeYes);
        employeeYes.setText("Yes");
        employeeYes.setToolTipText("Employee Yes");
        employeeYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeYesActionPerformed(evt);
            }
        });

        isEmployee.add(employeeNo);
        employeeNo.setSelected(true);
        employeeNo.setText("No");
        employeeNo.setToolTipText("employee No");

        admin.setText("Admin");

        isAdmin.add(adminYes);
        adminYes.setText("Yes");
        adminYes.setToolTipText("Admin Yes");

        isAdmin.add(adminNo);
        adminNo.setSelected(true);
        adminNo.setText("No");
        adminNo.setToolTipText("Admin No");

        collateral.setText("Collateral");

        hasCollateral.add(collateralYes);
        collateralYes.setText("Yes");

        hasCollateral.add(collateralNo);
        collateralNo.setSelected(true);
        collateralNo.setText("No");

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(collateral)
                            .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(scrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(address)
                                    .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contentLayout.createSequentialGroup()
                                            .addComponent(email)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(emailValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contentLayout.createSequentialGroup()
                                            .addComponent(mobile)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(mobileValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contentLayout.createSequentialGroup()
                                            .addComponent(cpassword)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cPasswordValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contentLayout.createSequentialGroup()
                                            .addComponent(userName)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(userNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, contentLayout.createSequentialGroup()
                                            .addComponent(password)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(passwordValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(contentLayout.createSequentialGroup()
                                            .addComponent(firstName)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(firstNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(contentLayout.createSequentialGroup()
                                            .addComponent(lastName)
                                            .addGap(83, 83, 83)
                                            .addComponent(lastNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(contentLayout.createSequentialGroup()
                                    .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(employee)
                                        .addComponent(admin))
                                    .addGap(88, 88, 88)
                                    .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(contentLayout.createSequentialGroup()
                                            .addComponent(collateralYes)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(collateralNo))
                                        .addGroup(contentLayout.createSequentialGroup()
                                            .addComponent(employeeYes)
                                            .addGap(49, 49, 49)
                                            .addComponent(employeeNo))
                                        .addGroup(contentLayout.createSequentialGroup()
                                            .addComponent(adminYes)
                                            .addGap(49, 49, 49)
                                            .addComponent(adminNo)))))))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(244, 244, 244)
                        .addComponent(submit)
                        .addGap(72, 72, 72)
                        .addComponent(reset)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(contentLayout.createSequentialGroup()
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(formTitle))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(successMsg)))
                .addGap(0, 347, Short.MAX_VALUE))
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(formTitle)
                .addGap(51, 51, 51)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastName)
                    .addComponent(lastNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstName)
                    .addComponent(firstNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userName)
                    .addComponent(userNameValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password)
                    .addComponent(passwordValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpassword)
                    .addComponent(cPasswordValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mobile)
                    .addComponent(mobileValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email)
                    .addComponent(emailValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(contentLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(address)))
                .addGap(37, 37, 37)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(employee)
                    .addComponent(employeeYes)
                    .addComponent(employeeNo))
                .addGap(37, 37, 37)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(admin)
                    .addComponent(adminYes)
                    .addComponent(adminNo))
                .addGap(43, 43, 43)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(collateral)
                    .addComponent(collateralYes)
                    .addComponent(collateralNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submit)
                    .addComponent(reset))
                .addGap(39, 39, 39)
                .addComponent(successMsg)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(content, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void userNameValueActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void mobileValueActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void employeeYesActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void submitActionPerformed(java.awt.event.ActionEvent evt) throws NoSuchAlgorithmException,  UnsupportedAudioFileException, LineUnavailableException, IOException  {                                       
        
        Signup signup = new Signup();
        //Manager manager = new Manager();
        
        //get the user entered details
        String lastName = lastNameValue.getText();
        String firstName = firstNameValue.getText();
        String userName = userNameValue.getText();
        String password = String.valueOf(passwordValue.getPassword());
        String cPassword = String.valueOf(cPasswordValue.getPassword());
        String mobile = mobileValue.getText();
        String address = addressValue.getText();
        String email = emailValue.getText();
        int is_employee = 0;
        int is_admin = 0;
        int hasCollateral = 0;

        if(employeeYes.isSelected()){
            System.out.println("Employee: Yes");
            is_employee = 1;
        }
        else if(employeeNo.isSelected()){
            System.out.println("Employee: No");
            is_employee = 0;
        }

        if(adminYes.isSelected()){
            System.out.println("Admin: Yes");
            is_admin = 1;
        }
        else if(adminNo.isSelected()){
            System.out.println("Admin: No");
            is_admin = 0;
        }

        if(collateralYes.isSelected()){
            System.out.println("Collateral: Yes");
            hasCollateral = 1;
        }
        else if(collateralNo.isSelected()){
            System.out.println("Collateral: No");
            hasCollateral = 0;
        }

        //password = confirm password, proceed
        if(password.equals(cPassword)){
            System.out.println("Password = Confirm Password");
            String encryptedSignUpPassword = SHA256.getSHA(password);

            boolean signUpSuccess = signup.signup(firstName, lastName, mobile, address, email, userName,
                    encryptedSignUpPassword, is_employee, is_admin, hasCollateral);

            Manager manager = new Manager();
            if (signUpSuccess) {
                System.out.println();
                System.out.println("You have successfully signed up");
                manager.loadAllData();

                Music.playSound("src/main/java/org/backend/music/success.wav");
                JOptionPane.showMessageDialog(null, "You have successfully signed up");
                

                //clear the fields
                setDefault();
            } else {
                System.out.println();
                System.out.println("Something went wrong. Signup Failed.");
                Music.playSound("src/main/java/org/backend/music/invalid.wav");
                JOptionPane.showMessageDialog(null, "Something went wrong. Signup Failed.");
            }
        }
        else {
            System.out.println();
            System.out.println("Invalid Password. Please try again.");
            Music.playSound("src/main/java/org/backend/music/invalid.wav");
            JOptionPane.showMessageDialog(null, "Invalid Password. Please try again.");
        }

        this.dispose();
    }                                      

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {                                      
        setDefault();
    }                                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SignUp dialog = new SignUp(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void setDefault(){

		String def = "";
		lastNameValue.setText(def);
		firstNameValue.setText(def);
		userNameValue.setText(def);
		passwordValue.setText(def);
        cPasswordValue.setText(def);
		addressValue.setText(def);
		mobileValue.setText(def);
		emailValue.setText(def);
        employeeNo.setSelected(true);
        adminNo.setSelected(true);
        collateralNo.setSelected(true);
	}
                      
}
