/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package org.userInterface;

import java.util.ArrayList;
import java.util.List;
import java.util.Vector;

import javax.swing.table.DefaultTableModel;

import org.backend.models.Account;
import org.backend.models.AccountChecking;
import org.backend.models.AccountSavings;
import org.backend.models.Manager;
import org.backend.models.Transaction;
import org.backend.models.User;
/**
 *
 * @author praneshjayasundar
 */
public class TransactionDetails extends javax.swing.JDialog {

    static User loggedInUserGlobal;
    /**
     * Creates new form TransactionDetails
     */
    public TransactionDetails(javax.swing.JDialog parent, boolean modal, User loggedInUser) {
        super(parent, modal);
        loggedInUserGlobal = loggedInUser;
        initComponents();
        setLocationRelativeTo(null);
        addAccountData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        formTitle = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        transactionDetails = new javax.swing.JTable();
        accountNumber = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        accountTable = new javax.swing.JTable();
        searchButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        
        formTitle.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        formTitle.setText("Transaction Details");

        transactionDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Transaction ID", "Account Number", "Initiating Customer ID", "Transaction Type", "Debit Amount", "Credit Amount", "Transaction Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(transactionDetails);
        transactionDetails.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        accountNumber.setText("Account Number");

        accountTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer ID", "Account Number", "Account Type", "Balance"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(accountTable);
        accountTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(accountNumber)
                        .addGap(46, 46, 46)
                        .addComponent(jScrollPane4))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1001, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(formTitle))
                .addGap(32, 32, 32))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(485, 485, 485)
                .addComponent(searchButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(accountNumber))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(searchButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(formTitle)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {                                             
        addTransactionData();
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransactionDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransactionDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransactionDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransactionDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TransactionDetails dialog = new TransactionDetails(new javax.swing.JDialog(), true, loggedInUserGlobal);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel accountNumber;
    private javax.swing.JTable accountTable;
    private javax.swing.JLabel formTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton searchButton;
    private javax.swing.JTable transactionDetails;
    // End of variables declaration

    public void addAccountData(){

        //add senders account data
        if (loggedInUserGlobal != null) {

            String[] columns = new String [] {
                "Customer ID", "Account Number", "Account Type", "Balance"
            };

            DefaultTableModel model = (DefaultTableModel)accountTable.getModel();
            model.setColumnIdentifiers(columns);

            Manager manager = new Manager();
            System.out.println("Enter Account Details");
            System.out.print("Account Number: ");
            //find account in manager accounts
            manager.loadAllData();
            loggedInUserGlobal = manager.getLoggedInUser(loggedInUserGlobal.getId());
            if (manager.getAccounts() != null) {
                for (Account account : manager.getAccounts()) {
                    if ((account.getCustomerId() == loggedInUserGlobal.getId() || loggedInUserGlobal.getIsAdmin() == 1) 
                        &&
                        account.getAccountStatus() == 1) {

                        System.out.println(account.getAccountType());
                        System.out.println(account.getAccountBalance());
                        System.out.println(account.getAccountNumber());
                        System.out.println(account.getCustomerId());
                        System.out.println(account.getAccountStatus());

                        //System.out.println(account);

                        Vector<Object> vector = new Vector<>();
                        vector.add(account.getCustomerId());
                        vector.add(account.getAccountNumber());
                        vector.add(account.getAccountType());
                        vector.add((Double)account.getAccountBalance());

                        model.addRow(vector);
                    }
                }
            } else {
                System.out.println("No Such Account Found");
            }
        } else {
            System.out.println("Please login first");
        }
    }
    
    public void addTransactionData(){

        String[] columns = new String [] {
            "Transaction ID", "Account Number", "Initiating Customer ID", "Transaction Type", "Debit Amount", "Credit Amount", "Transaction Status"
        };

        Manager manager = new Manager();

        DefaultTableModel modelAccount = (DefaultTableModel)accountTable.getModel();
        int accountSelectedRow = accountTable.getSelectedRow();
        String accountNumber = modelAccount.getValueAt(accountSelectedRow, 1).toString();


        DefaultTableModel modelTransaction = (DefaultTableModel)transactionDetails.getModel();
        modelTransaction.setColumnIdentifiers(columns);
        modelTransaction.setRowCount(0);

        //-----------------View Transaction Detail-----------------------//

        if (loggedInUserGlobal != null) {
            System.out.println("Enter Account Details");
            System.out.print("Account Number: ");
            //find account in manager accounts
            manager.loadAllData();
            loggedInUserGlobal = manager.getLoggedInUser(loggedInUserGlobal.getId());
            if (manager.getAccounts() != null && manager.getAccounts().size() > 0
            && manager.getAccountNumbers().contains(accountNumber)) {

                for (AccountSavings accountSavings : manager.getSavingsAccounts()) {
                    if ((loggedInUserGlobal.getIsAdmin()==1 ||
                            accountSavings.getCustomerId() == loggedInUserGlobal.getId()) &&
                            accountSavings.getAccountNumber().equals(accountNumber)) {
                        //view account transactions
                        System.out.println("Account Transactions: ");
                        if(accountSavings.getTransactions() != null &&
                                accountSavings.getTransactions().size() > 0) {
                            //accountSavings.viewTransactions();

                            for(int i=0; i<accountSavings.getTransactions().size(); i++){

                                Vector<Object> vector = new Vector<>();
                                vector.add(accountSavings.getTransactions().get(i).getTransactionId());
                                vector.add(accountSavings.getTransactions().get(i).getAccountNumber());
                                vector.add(accountSavings.getTransactions().get(i).getCustomerId());
                                vector.add(accountSavings.getTransactions().get(i).getTransactionType());
                                vector.add(accountSavings.getTransactions().get(i).getDebitAmount());
                                vector.add(accountSavings.getTransactions().get(i).getCreditAmount());
                                vector.add(accountSavings.getTransactions().get(i).getTransactionStatus());

                                modelTransaction.addRow(vector);
                            }

                        } else {
                            System.out.println("No Transactions Found");
                        }

                    }
                }
                for (AccountChecking checkingAccount : manager.getCheckingAccounts()) {
                    if ((loggedInUserGlobal.getIsAdmin()==1 ||
                            checkingAccount.getCustomerId() == loggedInUserGlobal.getId()) &&
                            checkingAccount.getAccountNumber().equals(accountNumber)) {
                        //view account transactions
                        System.out.println("Account Transactions: ");
                        if(checkingAccount.getTransactions()!=null &&
                                checkingAccount.getTransactions().size()>0) {
                            //checkingAccount.viewTransactions();

                            for(int i=0; i<checkingAccount.getTransactions().size(); i++){

                                Vector<Object> vector = new Vector<>();
                                vector.add(checkingAccount.getTransactions().get(i).getTransactionId());
                                vector.add(checkingAccount.getTransactions().get(i).getAccountNumber());
                                vector.add(checkingAccount.getTransactions().get(i).getCustomerId());
                                vector.add(checkingAccount.getTransactions().get(i).getTransactionType());
                                vector.add(checkingAccount.getTransactions().get(i).getDebitAmount());
                                vector.add(checkingAccount.getTransactions().get(i).getCreditAmount());
                                vector.add(checkingAccount.getTransactions().get(i).getTransactionStatus());

                                modelTransaction.addRow(vector);
                            }

                        } else{
                            System.out.println("No Transactions Found");
                        }
                    }
                }

            } else {
                System.out.println("No Such Account Found");
            }
        } else {
            System.out.println("Please login first");
        }
        //-----------------View Transaction Detail-----------------------//

    }
}
